lectures/wk11/finished/flask_app/main/routes.py
from flask import render_template, Blueprint, request, current_app, redirect, url_for

from flask_app.models import Post, User

import json

main = Blueprint('main', __name__)

@main.route("/")
def index():
    posts = Post.query.all()
    return render_template('index.html', title='Home', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/user/<username>")
def user_detail(username):
    user = User.query.filter_by(username=username).first()

    return render_template('user_detail.html', user=user)

@main.route("/csp_error_handling", methods=["POST"])
def report_handler():
    """
    Receives POST requests from the browser whenever the Content-Security-Policy 
    is violated. Processes the data and logs an easy-to-read version of the message
    in your console.
    """
    report = json.loads(request.data.decode())["csp-report"]

    # current_app.logger.info(json.dumps(report, indent=2))

    violation_desc = "\nViolated directive: %s, \nBlocked: %s, \nOriginal policy: %s \n" % (
        report["violated-directive"],
        report["blocked-uri"],
        report["original-policy"]
    )

    current_app.logger.info(violation_desc)
    return redirect(url_for("main.index"))

lectures/wk11/finished/flask_app/users/routes.py
from flask import render_template, url_for, redirect, request, current_app, Blueprint, session
from flask_login import login_user, current_user, logout_user, login_required

from flask_app import db, bcrypt
from flask_app.models import User, Post
from flask_app.users.forms import RegistrationForm, LoginForm, UpdateForm

import qrcode
import qrcode.image.svg as svg

from io import BytesIO

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        user = User(username=form.username.data, email=form.email.data, password=hashed)
        db.session.add(user)
        db.session.commit()

        # return redirect(url_for('users.login'))
        session['reg_username'] = user.username

        return redirect(url_for('users.tfa'))
    
    return render_template('register.html', title='Register', form=form)


@users.route("/tfa")
def tfa():
    if 'reg_username' not in session:
        return redirect(url_for('main.index'))

    headers = {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return render_template('tfa.html'), headers

@users.route("/qr_code")
def qr_code():
    if 'reg_username' not in session:
        return redirect(url_for('main.index'))
    
    user = User.query.filter_by(username=session['reg_username']).first()

    session.pop('reg_username')

    img = qrcode.make(user.get_auth_uri(), image_factory=svg.SvgPathImage)

    stream = BytesIO()

    img.save(stream)

    headers = {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return stream.getvalue(), headers


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for('users.account'))

    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    username = current_user.username
    logout_user()
    current_app.logger.info('%s logged out successfully', username)
    return redirect(url_for('main.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateForm()

    if form.validate_on_submit():
        current_user.username = form.username.data

        db.session.commit()

        return redirect(url_for('users.account'))
    
    elif request.method == 'GET':
        form.username.data = current_user.username
    
    return render_template('account.html', title='Account', form=form)

lectures/wk11/finished/flask_app/templates/about.html
{% extends "base.html" %}
{% block content %}
    <h2>About</h2>
    <p>This is a sample Flask app that manages users and keeps track of posts. It does not allow creating new posts, however.</p>
{% endblock %}

lectures/wk11/finished/flask_app/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h2>{{ current_user.username }}</h2>
        <p>{{ current_user.email }}</p>
    </div>
    <div>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div>
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div>
                {{ form.submit }}
            </div>
        </form>
    </div>
    <div>
        <h3>Your posts:</h3>
    </div>
    {% for post in current_user.posts %}
    <article>
        <div>
            <div>
                You, 
                <small>on {{ post.date.strftime('%B %d, %Y') }}, posted:</small>
            </div>
            <h2>{{ post.title }}</h2>
            <p>{{ post.content }}</p>
        </div>
    </article>
{% endfor %}
{% endblock %}

lectures/wk11/finished/flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href={{ url_for('static', filename='css/bootstrap.min.css' )}}> -->

    <link rel="stylesheet" href={{ url_for('static', filename='css/custom.css') }}>

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Flask App</title>
    {% endif %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">

            <a class="navbar-brand" href={{ url_for('main.index' )}}>Flask App</a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarToggle">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href={{ url_for('main.index') }} class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('main.about') }} class="nav-link">About</a>
                    </li>
                </ul>

                {% if current_user.is_authenticated %}
                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href={{ url_for('users.account' )}} class="nav-link">My Account</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.logout' )}} class="nav-link">Logout</a>
                    </li>
                </ul>

                {% else %}

                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href={{ url_for('users.login' )}} class="nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.register' )}} class="nav-link">Register</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </header>

    <main class="container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                Content
            </div> 
        </div>
    </main>






    {#{% block content %}{% endblock %}#}
<!-- 
    <script src={{ url_for('static', filename='js/jquery.min.js' )}}></script>
    <script src={{ url_for('static', filename='js/popper.min.js' )}}></script>
    <script src={{ url_for('static', filename='js/bootstrap.min.js' )}}></script> -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

lectures/wk11/finished/flask_app/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h1>Posts</h1>
    </div>
    {% for post in posts %}
        <article class="content-section">
            <div>
                <div>
                    <a href={{ url_for('main.user_detail', username=post.author.username) }}>{{ post.author.username }}</a>
                    <small>on {{ post.date.strftime('%B %d, %Y') }} posted:</small>
                </div>
                <h2>{{ post.title }}</h2>
                <p>{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock %}

lectures/wk11/finished/flask_app/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h2>Log In</h2>
    </div>
    <div>
        If you <b>don't</b> have an account, then <a href={{ url_for('users.register') }}>Register!</a>
    </div>
    <div>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div>
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>

            {% endif %}
            </div>
            <div>
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
            </div>
            <div>
                {{ form.token.label(class="form-control-label green-text") }}
                {{ form.token(class="form-control form-control-md") }}

                {% if form.token.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.token.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>

            {% endif %}
            </div>
            <div>
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
{% endblock %}

lectures/wk11/finished/flask_app/templates/register.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h2>Registration</h2>
    </div>
    <div>
        If you already have an account, then just <a href={{ url_for('users.login') }}>Log In!</a>
    </div>
    <!-- Registration Form: -->
    <div>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div>
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>

{% endblock %}

lectures/wk11/finished/flask_app/templates/tfa.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h2>Two-Factor Auth Enrollment</h2>
    </div>
    <div>
        This website requires mandatory 2FA enrollment. 
    </div>
    <!-- Registration Form: -->
    <p>
        Use a authenticator app to enroll with us! You will need to use this app to login in the future.
    </p>
    <img src={{ url_for('users.qr_code') }} alt="QR Code for 2FA">

    <div>
        When you're done, you can go to the <a href={{ url_for('users.login') }}>Login page</a>!
    </div>


{% endblock %}

lectures/wk11/finished/flask_app/templates/user_detail.html
{% extends "base.html" %}
{% block content %}
    <div>
        {{ user.username }}'s Posts
    </div>
    {% for post in user.posts %}
    <article>
        <div>
            <h2>{{ post.title }}</h2>
            <div>
                <small>{{ post.date.strftime('%B %d, %Y') }}</small>
            </div>
            <p>{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
{% endblock %}